services:
  - type: web
    name: italia-caf-immigration-site
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
